grails-app/domain/com/Author.groovy
package com

class Author {
    String name
    static hasMany = [books: Book]



}

grails-app/domain/com/Book.groovy
package com

class Book {
    String name
    static belongsTo = [author: Author]
}

grails-app/domain/com/College.groovy
package com

class College {

    static hasMany = [students: Student]
    static constraints = {
    }
}

grails-app/domain/com/Eye.groovy
package com

class Eye {
//    Face face
//    String name = "EYE1"
    static belongsTo = [face: Face]
    static constraints = {
    }
}

grails-app/domain/com/Face.groovy
package com

class Face {
//    Nose nose
    String name
    static hasOne = [nose: Nose]

//    String name = "Face1"
//    static hasMany = [eyes: Eye]
    static constraints = {
    }
}

grails-app/domain/com/Nose.groovy
package com

class Nose {
//    Face face
    String name
    static belongsTo = [face: Face]
    static constraints = {
    }
}

grails-app/domain/com/Student.groovy
package com

class Student {


    static belongsTo = [college: College]
    static constraints = {
    }
}

grails-app/domain/helloWorld/Person.groovy
package helloWorld

class Person {

    static constraints = {
    }
}

grails-app/domain/helloWorld/User.groovy
package helloWorld

class User {
    String username
    String age
    static constraints = {
        username(nullable: false)
        age(min: false)
    }
}

grails-app/controllers/UrlMappings.groovy
class UrlMappings {

    static mappings = {
        "/$controller/$action?/$id?(.$format)?"{
            constraints {
                // apply constraints here
            }
        }

        "/"(view:"/index")
        "500"(view:'/error')
        "404"(view:'/notFound')
    }
}

grails-app/controllers/com/AuthorController.groovy
package com

import static org.springframework.http.HttpStatus.*
import grails.transaction.Transactional

@Transactional(readOnly = true)
class AuthorController {

    static allowedMethods = [save: "POST", update: "PUT", delete: "DELETE"]

    def index(Integer max) {
        params.max = Math.min(max ?: 10, 100)
        respond Author.list(params), model:[authorCount: Author.count()]
    }

    def show(Author author) {
        respond author
    }

    def create() {
        respond new Author(params)
    }

    @Transactional
    def save(Author author) {
        if (author == null) {
            transactionStatus.setRollbackOnly()
            notFound()
            return
        }

        if (author.hasErrors()) {
            transactionStatus.setRollbackOnly()
            respond author.errors, view:'create'
            return
        }

        author.save flush:true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.created.message', args: [message(code: 'author.label', default: 'Author'), author.id])
                redirect author
            }
            '*' { respond author, [status: CREATED] }
        }
    }

    def edit(Author author) {
        respond author
    }

    @Transactional
    def update(Author author) {
        if (author == null) {
            transactionStatus.setRollbackOnly()
            notFound()
            return
        }

        if (author.hasErrors()) {
            transactionStatus.setRollbackOnly()
            respond author.errors, view:'edit'
            return
        }

        author.save flush:true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.updated.message', args: [message(code: 'author.label', default: 'Author'), author.id])
                redirect author
            }
            '*'{ respond author, [status: OK] }
        }
    }

    @Transactional
    def delete(Author author) {

        if (author == null) {
            transactionStatus.setRollbackOnly()
            notFound()
            return
        }

        author.delete flush:true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.deleted.message', args: [message(code: 'author.label', default: 'Author'), author.id])
                redirect action:"index", method:"GET"
            }
            '*'{ render status: NO_CONTENT }
        }
    }

    protected void notFound() {
        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.not.found.message', args: [message(code: 'author.label', default: 'Author'), params.id])
                redirect action: "index", method: "GET"
            }
            '*'{ render status: NOT_FOUND }
        }
    }
}

grails-app/controllers/com/BookController.groovy
package com

class BookController {

    def index() {
        Author author = new Author()
        author.name = "A1"
        Book book = new Book()
        book.name = "Book1"
        book.author = author
        author.addToBooks(book)
        author.save(flush: true)
        render "ok"
    }


}

grails-app/controllers/com/CollegeController.groovy
package com

class CollegeController {

    def index() { }
}

grails-app/controllers/com/DemoController.groovy
package com

class DemoController {
    static scaffold = Author

    def index() {
//        Author author = new Author(name: 'a1').save(flush: true)
//        Book book = new Book(name: 'b1').save(flush: true)
//        author.addToBooks(book).save(flush: true)
//        Book book2 = new Book(name: 'b1').save(flush: true)
//        author.addToBooks(book2).save(flush: true)

        Author author = new Author(name: 'a1').save(flush: true)
        Book book = new Book(name: 'b1', author: author).save(flush: true)
        author.addToBooks(book).save(flush: true)
        Book book2 = new Book(name: 'b2', author: author).save(flush: true)
        author.addToBooks(book2).save(flush: true)
//
//
//        Author author = new Author(name: 'a1').save(flush: true)
//        Book book = new Book(name: 'b1', author: author).save(flush: true)
//        Book book2 = new Book(name: 'b2', author: author).save(flush: true)
//        println "author   " + author.books
        render author.books ?: 'null'
    }
}

grails-app/controllers/com/EyeController.groovy
package com

class EyeController {

    def index() {
        Face face = null
        Eye eye = null
        Face.withSession { session ->
            face = new Face().save(flush: true)
            eye = new Eye(face: face).save(flush: true)
            session.flush()
        }

//        Thread.sleep(30000);
        Face.withNewSession {
            println "face -> eyes" + Face.get(1).eyes
        }


        render "Success "
    }
}

grails-app/controllers/com/FaceController.groovy
package com

class FaceController {


    def index() {
//        Face face = new Face()
//        face.name="Face1"
//        Nose nose = new Nose()
//        nose.name="Nose 1"
//
//        nose.face = face
//        face.nose = nose
//
//        face.save(flush: true)

//        Nose nose = Nose.get(1)
//        println "   nose " + nose.face

//        Face face = Face.get(1)
//        face.delete(flush: true)
        Nose nose = Nose.findById(2)
        nose.name = "Nose 2"
        nose.save(flush: true)
        nose.delete(flush: true)
        render "success"
    }
}

grails-app/controllers/com/NoseController.groovy
package com

class NoseController {

    def index() {

        Face face = new Face()
        Nose nose = new Nose()
        nose.face = face
        face.nose = nose
        face.save(flush: true)

        println "=====face-> nose " + face.nose
        println "=====nose-> face " + nose.face


        render "ok"
    }
}

grails-app/controllers/com/StudentController.groovy
package com

class StudentController {

    def index() {
        College college = new College()
        Student student = new Student()
        student.college = college
        college.addToStudents(student)
        college.save(flush: true)

        println "college students  " + college.students
        println "student -> college " + student.college
        render "ok"
    }
}

grails-app/views/author/create.gsp
<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="main" />
        <g:set var="entityName" value="${message(code: 'author.label', default: 'Author')}" />
        <title><g:message code="default.create.label" args="[entityName]" /></title>
    </head>
    <body>
        <a href="#create-author" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
        <div class="nav" role="navigation">
            <ul>
                <li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
                <li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
            </ul>
        </div>
        <div id="create-author" class="content scaffold-create" role="main">
            <h1><g:message code="default.create.label" args="[entityName]" /></h1>
            <g:if test="${flash.message}">
            <div class="message" role="status">${flash.message}</div>
            </g:if>
            <g:hasErrors bean="${this.author}">
            <ul class="errors" role="alert">
                <g:eachError bean="${this.author}" var="error">
                <li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
                </g:eachError>
            </ul>
            </g:hasErrors>
            <g:form action="save">
                <fieldset class="form">
                    <f:all bean="author"/>
                </fieldset>
                <fieldset class="buttons">
                    <g:submitButton name="create" class="save" value="${message(code: 'default.button.create.label', default: 'Create')}" />
                </fieldset>
            </g:form>
        </div>
    </body>
</html>

grails-app/views/author/edit.gsp
<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="main" />
        <g:set var="entityName" value="${message(code: 'author.label', default: 'Author')}" />
        <title><g:message code="default.edit.label" args="[entityName]" /></title>
    </head>
    <body>
        <a href="#edit-author" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
        <div class="nav" role="navigation">
            <ul>
                <li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
                <li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
                <li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
            </ul>
        </div>
        <div id="edit-author" class="content scaffold-edit" role="main">
            <h1><g:message code="default.edit.label" args="[entityName]" /></h1>
            <g:if test="${flash.message}">
            <div class="message" role="status">${flash.message}</div>
            </g:if>
            <g:hasErrors bean="${this.author}">
            <ul class="errors" role="alert">
                <g:eachError bean="${this.author}" var="error">
                <li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
                </g:eachError>
            </ul>
            </g:hasErrors>
            <g:form resource="${this.author}" method="PUT">
                <g:hiddenField name="version" value="${this.author?.version}" />
                <fieldset class="form">
                    <f:all bean="author"/>
                </fieldset>
                <fieldset class="buttons">
                    <input class="save" type="submit" value="${message(code: 'default.button.update.label', default: 'Update')}" />
                </fieldset>
            </g:form>
        </div>
    </body>
</html>

grails-app/views/author/index.gsp
<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="main" />
        <g:set var="entityName" value="${message(code: 'author.label', default: 'Author')}" />
        <title><g:message code="default.list.label" args="[entityName]" /></title>
    </head>
    <body>
        <a href="#list-author" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
        <div class="nav" role="navigation">
            <ul>
                <li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
                <li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
            </ul>
        </div>
        <div id="list-author" class="content scaffold-list" role="main">
            <h1><g:message code="default.list.label" args="[entityName]" /></h1>
            <g:if test="${flash.message}">
                <div class="message" role="status">${flash.message}</div>
            </g:if>
            <f:table collection="${authorList}" />

            <div class="pagination">
                <g:paginate total="${authorCount ?: 0}" />
            </div>
        </div>
    </body>
</html>

grails-app/views/author/show.gsp
<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="main" />
        <g:set var="entityName" value="${message(code: 'author.label', default: 'Author')}" />
        <title><g:message code="default.show.label" args="[entityName]" /></title>
    </head>
    <body>
        <a href="#show-author" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
        <div class="nav" role="navigation">
            <ul>
                <li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
                <li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
                <li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
            </ul>
        </div>
        <div id="show-author" class="content scaffold-show" role="main">
            <h1><g:message code="default.show.label" args="[entityName]" /></h1>
            <g:if test="${flash.message}">
            <div class="message" role="status">${flash.message}</div>
            </g:if>
            <f:display bean="author" />
            <g:form resource="${this.author}" method="DELETE">
                <fieldset class="buttons">
                    <g:link class="edit" action="edit" resource="${this.author}"><g:message code="default.button.edit.label" default="Edit" /></g:link>
                    <input class="delete" type="submit" value="${message(code: 'default.button.delete.label', default: 'Delete')}" onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');" />
                </fieldset>
            </g:form>
        </div>
    </body>
</html>

grails-app/views/layouts/main.gsp
<!doctype html>
<html lang="en" class="no-js">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title><g:layoutTitle default="Grails"/></title>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <asset:stylesheet src="application.css"/>
        <asset:javascript src="application.js"/>

        <g:layoutHead/>
    </head>
    <body>
        <div id="grailsLogo" role="banner"><a href="http://grails.org"><asset:image src="grails_logo.png" alt="Grails"/></a></div>
        <g:layoutBody/>
        <div class="footer" role="contentinfo"></div>
        <div id="spinner" class="spinner" style="display:none;"><g:message code="spinner.alt" default="Loading&hellip;"/></div>
    </body>
</html>